# Generated by Django 3.1.4 on 2021-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210402_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingentry',
            name='impact',
            field=models.IntegerField(default=0),
        ),
    ]
