# Generated by Django 3.1.4 on 2021-04-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recyclingentry_impact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recyclingentry',
            options={'ordering': ['-date']},
        ),
    ]
