# Generated by Django 3.1.4 on 2021-04-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210402_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingentry',
            name='impact',
            field=models.IntegerField(default=1),
        ),
    ]
