# Generated by Django 3.1.7 on 2021-04-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210402_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingdb',
            name='ewaste',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recyclingdb',
            name='lightning',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recyclingdb',
            name='secondhand',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
