# Generated by Django 3.1.7 on 2021-04-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210403_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclingentry',
            name='recyclingdb',
        ),
        migrations.RemoveField(
            model_name='recyclingentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='RecyclingDB',
        ),
        migrations.DeleteModel(
            name='RecyclingEntry',
        ),
    ]
