# Generated by Django 3.1.7 on 2021-04-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.PositiveSmallIntegerField(default=0)),
                ('tree', models.PositiveSmallIntegerField(default=0)),
                ('ewaste', models.PositiveSmallIntegerField(default=0)),
                ('lightning', models.PositiveSmallIntegerField(default=0)),
                ('secondhand', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='NTU')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recyclingType', models.TextField()),
                ('recyclingWeight', models.PositiveSmallIntegerField()),
                ('impact', models.IntegerField(default=1)),
                ('recyclingdb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recyclinghistory.recyclingdb')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
