# Generated by Django 3.1.7 on 2021-04-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recyclinghistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclingentry',
            name='recyclingdb',
        ),
        migrations.DeleteModel(
            name='RecyclingDB',
        ),
    ]
