# Generated by Django 3.1.7 on 2021-04-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recyclinghistory', '0003_recyclingentry_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclingentry',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='recyclingentry',
            name='tree',
        ),
    ]
